---
version: "3.8"
services:
  movies:
    image: sirisha11/movies
    ports:
      - 81:80
    deploy:
      replicas: 3
  train:
    image: sirisha11/train
    ports:
      - 82:80
    deploy:
      replicas: 3
  dth:
    image: sirisha11/dth
    ports:
      - 83:80
    deploy:
      replicas: 3
