---
version: "3.8"
services:
  gmail:
    image: sirisha11/gmail
    ports:
      - 81:80
    deploy:
      replicas: 3
  office:
    image: sirisha11/office
    ports:
      - 82:80
    deploy:
      replicas: 3
  server:
    image: sirisha11/server
    ports:
      - 83:80
    deploy:
      replicas: 3
  app:
    image: sirisha11/app
    ports:
      - 84:80
    deploy:
      replicas: 3
